### ISSUE TITLE
The mysterious 4px gap in between images - CodeBlocQ

### ISSUE THREAD

**Issue by klugjo** [klugjo/klugjo.github.io#17]
http://www.codeblocq.com/2016/09/The-mysterious-4px-gap-in-between-images/

**Comment by Malvoz** [comment]
```CSS
img {
  vertical-align: middle
}
```

:v:
